const roomUsage = {
  'Least Used Rooms': {
    '% Share of All Meetings': {
      36: 1.0,
      37: 1.0,
      38: 1.0,
      39: 1.0,
      40: 1.0,
      41: 1.0,
      42: 1.0,
      43: 1.0,
      44: 1.0,
      45: 1.0,
    },
    Meetings: {
      36: 2,
      37: 2,
      38: 2,
      39: 2,
      40: 1,
      41: 1,
      42: 1,
      43: 1,
      44: 1,
      45: 1,
    },
    Room: {
      36: 'Nairobi - 1st Floor SingleBlock A Dodoma (1)',
      37: 'Nairobi - Container Asmara(3)',
      38: 'Nairobi - 1st Floor SingleBlock A Tunis (1)',
      39: 'Nairobi -  1st Floor SingleBlock B  Tiwi (1)',
      40: 'Nairobi - 1st Floor SingleBlock A LibreVille (1)',
      41: 'Nairobi - 1st Floor SingleBlock A Bangui (1)',
      42: 'Nairobi - 2nd Floor SingleBlock B Midgar (6)',
      43: 'Nairobi - 2nd Floor SingleBlock B  Pandora (6)',
      44: 'Nairobi - 1st Floor SingleBlock A Monrovia (1)',
      45: 'Nairobi - 2nd Floor SingleBlock A Moroni (1)',
    },
  },
  'Most Used Rooms': {
    '% Share of All Meetings': {
      0: 5.0,
      1: 5.0,
      2: 4.0,
      3: 4.0,
      4: 4.0,
      5: 4.0,
      6: 4.0,
      7: 3.0,
      8: 3.0,
      9: 3.0,
    },
    Meetings: {
      0: 9,
      1: 9,
      2: 7,
      3: 6,
      4: 6,
      5: 6,
      6: 6,
      7: 5,
      8: 5,
      9: 5,
    },
    Room: {
      0: 'Nairobi - 1st Floor SingleBlock B - Ol Karia (1)',
      1: 'Nairobi -  2nd Floor SingleBlock A Free Town (6)',
      2: 'Nairobi - 1st Floor SingleBlock A Lome (6)',
      3: 'Nairobi - 1st Floor SingleBlock B  Wasini (2)',
      4: 'Nairobi - 1st Floor SingleBlock B Oculus (14)',
      5: 'Nairobi - 2nd Floor SingleBlock A Victoria (2)',
      6: 'Nairobi -  Container Kigali(1)',
      7: 'Nairobi - 2nd Floor SingleBlock A Mbabane (2)',
      8: 'Nairobi - Container Maputo(1)',
      9: 'Nairobi - 1st Floor SingleBlock A Porto-Novo (2)',
    },
  },
};

export default roomUsage;
