const selectMockData = [
  {
    name: 'Building',
    id: 'setupBuilding',
    value: 'Buildings',
    placeholder: 'Building 1',
    options: ['building'],
  },
  {
    name: 'all Floors',
    id: 'floors',
    value: 'All floors',
    placeholder: 'All Floors',
    options: ['All Floors'],
  },
  {
    name: 'all wings',
    id: 'wings',
    value: 'All wings',
    placeholder: 'All wings',
    options: ['All wings'],
  },
];

// Mock data for rooms
const roomsMockData = [
  {
    roomName: 'Obudu',
    wingName: 'Safari',
    floorName: '1st floor',
    numberOfSeats: 6,
    numberOfResources: 27,
  },
  {
    roomName: 'Empire State',
    wingName: 'Big Apple',
    floorName: '4th floor',
    numberOfSeats: 12,
    numberOfResources: 27,
  },
  {
    roomName: 'Ike-ogosi',
    wingName: 'Kampala',
    floorName: '3rd floor',
    numberOfSeats: 6,
    numberOfResources: 27,
  },
];

const meetingRoomTabMockData = [
  {
    capacity: 5,
    id: 3,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 1',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 332,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 2',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 45,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 3',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 98,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 4',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 0,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 5',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 4,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 6',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 7,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 7',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
  {
    capacity: 5,
    id: 9,
    imageUrl: 'https://www.officelovin.com/wp-content/uploads/2016/10/andela-office-main-1.jpg',
    name: 'Room 8',
    roomLabels: ['Label 1', 'Label 2', 'Label 3'],
    roomType: 'Room type',
    resources: [],
    'Symbol(id)': 'Room:6',
  },
];

export { selectMockData, roomsMockData, meetingRoomTabMockData };
